### ISSUE TITLE
The doc, the command line tool help and the module API are inconsistent

### ISSUE THREAD

**Issue by astorije** [w3c/third-party-resources-checker#11]
I noticed the whitelist format has recently changed, from a text file (one resource per line) to a JSON file (split between domains and URLs). It seems like [the README section](https://github.com/w3c/third-party-resources-checker#standalone) and the [command line tool help](https://github.com/w3c/third-party-resources-checker/blob/c074fd2e18294b8845ad785cac704764433b2f21/bin/third-party-resources-checker#L10) now differ. @deniak, did you forget to update the latter one or is it normal (like work in progress?)

Also, the documentation on [how to use the tool as a module](https://github.com/w3c/third-party-resources-checker#as-a-module) didn't change. The standalone mode now refers to external domains/URLs while the module mode mentions external resources, which is confusing. Did the module call method change as well and the doc wasn't updated, or does this way of calling it actually differs from the standalone mode? If so, I think the optional `Array` of `String` should actually be an `Object` to reflect the standalone mode.

Let me know if I am unclear :-)

**Comment by deniak** [comment]
> I noticed the whitelist format has recently changed, from a text file (one resource per line) to a JSON file (split between domains and URLs). It seems like the README section and the command line tool help now differ. @deniak, did you forget to update the latter one or is it normal (like work in progress?)

Indeed, I forgot to update the CLI. Done in #14. Thanks for catching that.

> Also, the documentation on how to use the tool as a module didn't change. The standalone mode now refers to external domains/URLs while the module mode mentions external resources, which is confusing. Did the module call method change as well and the doc wasn't updated, or does this way of calling it actually differs from the standalone mode? If so, I think the optional Array of String should actually be an Object to reflect the standalone mode.

Yes, it didn't change because the doc doesn't say anything about the format of the whitelist. So I assume, people will follow the format described in the standalone mode. Regarding the result, it still returns a `Promise` with the exit code and the optional `Array` of `String`.

**Comment by astorije** [comment]
> Yes, it didn't change because the doc doesn't say anything about the format of the whitelist. So I assume, people will follow the format described in the standalone mode. Regarding the result, it still returns a `Promise` with the exit code and the optional `Array` of `String`.

OK, I'll update the doc for the whitelist. Now that it's a JSON, it really is the same whether you send a JSON file or a JS object, that's cool!
