### ISSUE TITLE
Replace phantomjs-prebuilt with nightmare

### ISSUE THREAD

**Issue by tripu** [w3c/third-party-resources-checker#22]
cf https://github.com/w3c/echidna/issues/256#issuecomment-228657645

**Comment by dontcallmedom** [comment]
Let me express some scepticism; while there is no doubt that electron/nightmare is a better headless browser, it requires running an xfvb server and consumes a lot more memory than phantomjs. While getting a top-of-the-notch browser for ReSpec makes sense, for the very small bit of processing done in this tool, I fear it will be an overkill.

**Comment by tripu** [comment]
Sounds reasonable to me. I didn't think of that, thanks!
